# Use the official Nginx image as the base image
FROM nginx

# Copy your index.html file into the container's default Nginx directory
COPY index.html /usr/share/nginx/html/

# replace ##DATE## with current date in index.html
RUN sed -i "s/##DATE##/$(date)/" /usr/share/nginx/html/index.html