image:
  registry: public.ecr.aws/y1c4k6j6
containerPorts:
  http: 80
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
    - host: example.com
      paths:
        - path: /*
          backend:
            serviceName: nginx
            servicePort: http
