name: Build

on:
  workflow_dispatch:

env:
  AWS_ECR_REGION: us-east-1 # AWS region must be us-east-1 for public ECR
  AWS_EKS_REGION: eu-central-1
  ECR_REPOSITORY: pdevops-nginx
  ECR_PUBLIC: public.ecr.aws/y1c4k6j6
  IMAGE_TAG: ${{ github.sha }}
  EC2_HOST: "ec2-01.test-01.aws.perfect-devops.eu"
  EKS_HOST: "test-02-cluster.test-02.aws.perfect-devops.eu"
  HELM_CHART_NAME: bitnami/nginx
  HELM_CHART_VERSION: 15.3.1
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  EKS_CLUSTER_NAME: "test-02-cluster"
  KUBECONFIG_PATH: "~/.kube/config"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Amazon ECR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.aws
          push: false
          tags: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Tag Docker image
        id: tag-image
        run: echo "image-uri=${{ env.ECR_PUBLIC }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Push Docker image to Amazon ECR
        id: push-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.aws
          push: true
          tags: ${{ steps.tag-image.outputs.image-uri }}
    outputs:
      image-uri: ${{ steps.tag-image.outputs.image-uri }}
