name: CI/CD Pipeline

on:
  workflow_dispatch:

env:
  AWS_ECR_REGION: us-east-1 # AWS region must be us-east-1 for public ECR
  AWS_EKS_REGION: eu-central-1
  ECR_REPOSITORY: pdevops-nginx
  ECR_PUBLIC: public.ecr.aws/y1c4k6j6
  IMAGE_TAG: ${{ github.sha }}
  EC2_HOST: "ec2-01.test-01.aws.perfect-devops.eu"
  EKS_HOST: "test-02-cluster.test-02.aws.perfect-devops.eu"
  HELM_CHART_NAME: bitnami/nginx
  HELM_CHART_VERSION: 15.3.1
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  EKS_CLUSTER_NAME: "test-02-cluster"
  KUBECONFIG_PATH: "~/.kube/config"

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    name: Deploy to AWS EC2 (docker)
    environment:
      name: development
      url: "http://${{ env.EC2_HOST }}"
    steps:
      - name: Deploy Docker image to Amazon EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop nginx || true
            docker rm nginx || true
            docker pull ${{ env.ECR_PUBLIC }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker run -d --name nginx -p 80:80 ${{ env.ECR_PUBLIC }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
